name: Build and Release

on:
  workflow_call:
    inputs:
      release-version:
        required: true
        type: string
      draft-flag:
        type: string
        default: " "
    secrets:
      XCFRAMEWORK_SIGNING_TOKEN:
        required: true

jobs:
  build:
    runs-on: macos-14
    timeout-minutes: 30
    steps:
      - run: sudo xcode-select --switch /Applications/Xcode_15.1.app
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: brew install ghr
      - name: Build Jigra and Cordova
        run: ./build-jig ${{ inputs.release-version }}
      - name: Sign Jigra xcframework
        uses: familyjs/sign-xcf@main
        with:
          cert-token: ${{ secrets.XCFRAMEWORK_SIGNING_TOKEN }}
          xcframework-path: Jigra.xcframework
      - name: Sign Cordova xcframework
        uses: familyjs/sign-xcf@main
        with:
          cert-token: ${{ secrets.XCFRAMEWORK_SIGNING_TOKEN }}
          xcframework-path: Cordova.xcframework
      - name: Package Jigra and Cordova
        run: ./package-jig ${{ inputs.release-version }}
      - name: Push manifest update
        uses: EndBug/add-and-commit@v9
      - name: Create Release
        run: ghr -token ${{ secrets.GITHUB_TOKEN }} -name ${{ inputs.release-version }} ${{ inputs.draft-flag }} -replace ${{ inputs.release-version }} frameworks
